# This file is generated by gyp; do not edit.

TOOLSET := target
TARGET := make_ffmpeg_asm_lib
### Rules for action "make_library":
quiet_cmd_make_ffmpeg_asm_lib_make_library = ACTION Packate ffmpeg assembly into $(obj)/gen/third_party/ffmpeg/libffmpegasm.a. $@
cmd_make_ffmpeg_asm_lib_make_library = export LD_LIBRARY_PATH=$(builddir)/lib.host:$(builddir)/lib.target:$$LD_LIBRARY_PATH; cd third_party/ffmpeg; mkdir -p $(obj)/gen/third_party/ffmpeg; ar rcs "$(obj)/gen/third_party/ffmpeg/libffmpegasm.a" "$(obj)/gen/third_party/ffmpeg/deinterlace.o" "$(obj)/gen/third_party/ffmpeg/dsputil_yasm.o" "$(obj)/gen/third_party/ffmpeg/fft_mmx.o" "$(obj)/gen/third_party/ffmpeg/h264_chromamc.o" "$(obj)/gen/third_party/ffmpeg/vp3dsp.o"

$(obj)/gen/third_party/ffmpeg/libffmpegasm.a: obj := $(abs_obj)

$(obj)/gen/third_party/ffmpeg/libffmpegasm.a: builddir := $(abs_builddir)

$(obj)/gen/third_party/ffmpeg/libffmpegasm.a: TOOLSET := $(TOOLSET)
$(obj)/gen/third_party/ffmpeg/libffmpegasm.a: $(obj)/gen/third_party/ffmpeg/deinterlace.o $(obj)/gen/third_party/ffmpeg/dsputil_yasm.o $(obj)/gen/third_party/ffmpeg/fft_mmx.o $(obj)/gen/third_party/ffmpeg/h264_chromamc.o $(obj)/gen/third_party/ffmpeg/vp3dsp.o FORCE_DO_CMD
	$(call do_cmd,make_ffmpeg_asm_lib_make_library)

all_deps += $(obj)/gen/third_party/ffmpeg/libffmpegasm.a
action_make_ffmpeg_asm_lib_make_library_outputs := $(obj)/gen/third_party/ffmpeg/libffmpegasm.a


### Rules for final target.
# Build our special outputs first.
$(obj).target/third_party/ffmpeg/make_ffmpeg_asm_lib.stamp: | $(action_make_ffmpeg_asm_lib_make_library_outputs)

# Preserve order dependency of special output on deps.
$(action_make_ffmpeg_asm_lib_make_library_outputs): | $(obj).target/third_party/ffmpeg/assemble_ffmpeg_asm.stamp

$(obj).target/third_party/ffmpeg/make_ffmpeg_asm_lib.stamp: TOOLSET := $(TOOLSET)
$(obj).target/third_party/ffmpeg/make_ffmpeg_asm_lib.stamp: $(obj).target/third_party/ffmpeg/assemble_ffmpeg_asm.stamp FORCE_DO_CMD
	$(call do_cmd,touch)

all_deps += $(obj).target/third_party/ffmpeg/make_ffmpeg_asm_lib.stamp
# Add target alias
.PHONY: make_ffmpeg_asm_lib
make_ffmpeg_asm_lib: $(obj).target/third_party/ffmpeg/make_ffmpeg_asm_lib.stamp

# Add target alias to "all" target.
.PHONY: all
all: make_ffmpeg_asm_lib

